[project]
name = "pydm"
dynamic = ["version"]
description = "A modern Python download manager."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pyside6>=6.11.1",
]

[project.scripts]
pydm = "pydm.app:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.dynamic]
version = {attr = "pydm.version.__version__"}

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
